import { ReconstructionProject } from "./types";

export const SAMPLE_PROJECTS: ReconstructionProject[] = [
  {
    id: "proj-khadki-basalt",
    title: "Khadki Basalt Open-Pit Quarry - Section 4",
    clientRef: "MIN-GEO-2026-088",
    description: "High-resolution single-pass drone photogrammetry capturing terraced basalt quarry faces, haul ramps, and excavation volumes.",
    locationName: "Khadki Basalt Formation, Maharashtra",
    country: "India",
    coordinates: {
      lat: 18.7324,
      lng: 73.8567,
    },
    crs: "EPSG:32643 (WGS 84 / UTM Zone 43N)",
    areaHectares: 14.8,
    gsdCmPerPixel: 1.84,
    reprojectionErrorPx: 0.62,
    pointCloudSize: 3420000,
    triangleCount: 684000,
    status: "completed",
    progressPercent: 100,
    currentStage: "Dense reconstruction & texture projection complete",
    droneModel: "DJI Matrice 350 RTK",
    cameraSensor: "Zenmuse P1 (45MP Full-Frame 35mm)",
    focalLengthMm: 35.0,
    flightAltitudeM: 65.4,
    avgFlightSpeedMs: 5.2,
    captureDate: "2026-08-14 09:24 IST",
    videoDurationSec: 184,
    fps: 30,
    totalVideoFrames: 5520,
    extractedKeyframes: 368,
    thumbnailUrl: "/images/quarry.jpg",
    elevation: {
      minM: 542.1,
      maxM: 628.7,
      avgM: 585.4,
    },
    stages: [
      {
        id: "stg-1",
        name: "Optical Flow & Keyframe Extraction",
        category: "ingest",
        status: "completed",
        progress: 100,
        durationSec: 14,
        logMessage: "368 keyframes extracted with 82% longitudinal overlap and 0.94 blur threshold",
        details: "Single-pass 4K 60fps stream decoded via hardware accelerated NVDEC; adaptive motion-compensated sampling."
      },
      {
        id: "stg-2",
        name: "Feature Detection & SIFT Matching",
        category: "sfm",
        status: "completed",
        progress: 100,
        durationSec: 38,
        logMessage: "1,248,900 feature descriptors matched with epipolar geometric verification",
        details: "Scale-Invariant Feature Transform with Lowe's ratio test (0.75) and RANSAC essential matrix filter."
      },
      {
        id: "stg-3",
        name: "Bundle Adjustment & Camera Poses",
        category: "sfm",
        status: "completed",
        progress: 100,
        durationSec: 29,
        logMessage: "Sparse point cloud solved with 0.62 px mean reprojection error",
        details: "Levenberg-Marquardt non-linear least squares optimization with RTK GPS prior weighting."
      },
      {
        id: "stg-4",
        name: "Multi-View Stereo (MVS) Dense Cloud",
        category: "mvs",
        status: "completed",
        progress: 100,
        durationSec: 64,
        logMessage: "3,420,000 dense points generated at 1.84 cm/px GSD",
        details: "Patch-match stereo depth map fusion with geometric consistency check and normal filtering."
      },
      {
        id: "stg-5",
        name: "Poisson Surface Meshing & Texturing",
        category: "mesh",
        status: "completed",
        progress: 100,
        durationSec: 42,
        logMessage: "684,000 triangle manifold mesh reconstructed with 8K UV atlas texture",
        details: "Screened Poisson Surface Reconstruction (octree depth 11) with illumination-equalized texture blending."
      }
    ],
    telemetry: [
      { timeSec: 0, lat: 18.7321, lng: 73.8561, altitudeM: 65.0, speedMs: 5.1, pitchDeg: -35.2, rollDeg: 1.1, yawDeg: 42.0, frameIndex: 1, iso: 100, shutter: "1/1000s" },
      { timeSec: 25, lat: 18.7323, lng: 73.8564, altitudeM: 65.8, speedMs: 5.3, pitchDeg: -36.0, rollDeg: 0.8, yawDeg: 43.5, frameIndex: 750, iso: 100, shutter: "1/1000s" },
      { timeSec: 50, lat: 18.7326, lng: 73.8568, altitudeM: 66.2, speedMs: 5.0, pitchDeg: -38.4, rollDeg: -0.5, yawDeg: 48.2, frameIndex: 1500, iso: 100, shutter: "1/1250s" },
      { timeSec: 75, lat: 18.7329, lng: 73.8572, altitudeM: 65.9, speedMs: 5.2, pitchDeg: -40.1, rollDeg: 1.4, yawDeg: 54.0, frameIndex: 2250, iso: 100, shutter: "1/1250s" },
      { timeSec: 100, lat: 18.7331, lng: 73.8575, altitudeM: 64.7, speedMs: 5.4, pitchDeg: -37.8, rollDeg: -1.2, yawDeg: 62.1, frameIndex: 3000, iso: 100, shutter: "1/1000s" },
      { timeSec: 125, lat: 18.7334, lng: 73.8579, altitudeM: 65.5, speedMs: 5.1, pitchDeg: -36.5, rollDeg: 0.3, yawDeg: 68.4, frameIndex: 3750, iso: 100, shutter: "1/1000s" },
      { timeSec: 150, lat: 18.7336, lng: 73.8582, altitudeM: 66.0, speedMs: 5.2, pitchDeg: -35.9, rollDeg: 0.9, yawDeg: 71.0, frameIndex: 4500, iso: 100, shutter: "1/1000s" },
      { timeSec: 184, lat: 18.7338, lng: 73.8585, altitudeM: 65.2, speedMs: 4.8, pitchDeg: -35.0, rollDeg: 0.2, yawDeg: 74.5, frameIndex: 5520, iso: 100, shutter: "1/1000s" },
    ],
    gcps: [
      { id: "gcp-1", name: "GCP-101 (Bench Alpha)", lat: 18.7322, lng: 73.8562, elevationM: 545.2, residualErrorM: 0.014 },
      { id: "gcp-2", name: "GCP-102 (Crusher Edge)", lat: 18.7328, lng: 73.8571, elevationM: 588.6, residualErrorM: 0.018 },
      { id: "gcp-3", name: "GCP-103 (Upper Haul)", lat: 18.7335, lng: 73.8581, elevationM: 622.1, residualErrorM: 0.012 },
    ],
    artifacts: {
      objMeshSizeMb: 86.4,
      plyCloudSizeMb: 142.1,
      lasCloudSizeMb: 118.6,
      geotiffDemMb: 34.2,
      orthomosaicMb: 168.0,
    }
  },
  {
    id: "proj-zanskar-ridge",
    title: "Zanskar River Canyon & Ridge Topography",
    clientRef: "BRO-HYDRO-2026-012",
    description: "Alpine steep-gradient canyon and riverbed survey for landslide hazard assessment and road alignment planning.",
    locationName: "Padum Gorge, Ladakh",
    country: "India",
    coordinates: {
      lat: 33.4682,
      lng: 76.9821,
    },
    crs: "EPSG:32643 (WGS 84 / UTM Zone 43N)",
    areaHectares: 28.5,
    gsdCmPerPixel: 2.45,
    reprojectionErrorPx: 0.74,
    pointCloudSize: 4850000,
    triangleCount: 970000,
    status: "completed",
    progressPercent: 100,
    currentStage: "Digital Elevation Model & Orthorectification complete",
    droneModel: "IdeaForge SWITCH UAV",
    cameraSensor: "Sony RX0 II (20MP 1-inch)",
    focalLengthMm: 24.0,
    flightAltitudeM: 110.0,
    avgFlightSpeedMs: 7.4,
    captureDate: "2026-07-22 11:45 IST",
    videoDurationSec: 240,
    fps: 30,
    totalVideoFrames: 7200,
    extractedKeyframes: 480,
    thumbnailUrl: "/images/alpine.jpg",
    elevation: {
      minM: 3520.0,
      maxM: 3942.5,
      avgM: 3710.2,
    },
    stages: [
      {
        id: "stg-1",
        name: "Optical Flow & Keyframe Extraction",
        category: "ingest",
        status: "completed",
        progress: 100,
        durationSec: 19,
        logMessage: "480 sharp keyframes extracted across 240-second high-altitude pass",
        details: "Shadow and cloud-filtered frame selection; contrast normalization."
      },
      {
        id: "stg-2",
        name: "Feature Detection & SIFT Matching",
        category: "sfm",
        status: "completed",
        progress: 100,
        durationSec: 52,
        logMessage: "1,890,200 feature correspondences matched across steep terrain",
        details: "Rotation-invariant descriptor matching with terrain parallax adjustment."
      },
      {
        id: "stg-3",
        name: "Bundle Adjustment & Camera Poses",
        category: "sfm",
        status: "completed",
        progress: 100,
        durationSec: 36,
        logMessage: "Sparse geometry converged; camera intrinsic calibration verified",
        details: "Global SfM reconstruction with gauge fixing against barometric altimeter."
      },
      {
        id: "stg-4",
        name: "Multi-View Stereo (MVS) Dense Cloud",
        category: "mvs",
        status: "completed",
        progress: 100,
        durationSec: 92,
        logMessage: "4,850,000 spatial 3D points computed",
        details: "Sub-pixel disparity mapping on canyon rock walls and river gravel banks."
      },
      {
        id: "stg-5",
        name: "Poisson Surface Meshing & Texturing",
        category: "mesh",
        status: "completed",
        progress: 100,
        durationSec: 58,
        logMessage: "970,000 polygon TIN model generated with DEM raster",
        details: "Watertight Delaunay-Poisson fusion with hydrologic stream enforcement."
      }
    ],
    telemetry: [
      { timeSec: 0, lat: 33.4678, lng: 76.9815, altitudeM: 110.0, speedMs: 7.2, pitchDeg: -45.0, rollDeg: 0.0, yawDeg: 12.0, frameIndex: 1, iso: 125, shutter: "1/1600s" },
      { timeSec: 60, lat: 33.4680, lng: 76.9818, altitudeM: 112.5, speedMs: 7.5, pitchDeg: -44.2, rollDeg: 1.2, yawDeg: 15.4, frameIndex: 1800, iso: 125, shutter: "1/1600s" },
      { timeSec: 120, lat: 33.4683, lng: 76.9822, altitudeM: 109.8, speedMs: 7.3, pitchDeg: -46.1, rollDeg: -0.8, yawDeg: 19.8, frameIndex: 3600, iso: 125, shutter: "1/1600s" },
      { timeSec: 180, lat: 33.4686, lng: 76.9826, altitudeM: 111.0, speedMs: 7.4, pitchDeg: -45.5, rollDeg: 0.5, yawDeg: 22.3, frameIndex: 5400, iso: 125, shutter: "1/1600s" },
      { timeSec: 240, lat: 33.4689, lng: 76.9830, altitudeM: 108.5, speedMs: 7.1, pitchDeg: -45.0, rollDeg: -0.2, yawDeg: 25.0, frameIndex: 7200, iso: 125, shutter: "1/1600s" },
    ],
    gcps: [
      { id: "gcp-201", name: "GCP-Z1 (River Bank)", lat: 33.4679, lng: 76.9816, elevationM: 3522.4, residualErrorM: 0.022 },
      { id: "gcp-202", name: "GCP-Z2 (Ridge Crest)", lat: 33.4688, lng: 76.9829, elevationM: 3938.1, residualErrorM: 0.029 },
    ],
    artifacts: {
      objMeshSizeMb: 114.2,
      plyCloudSizeMb: 198.5,
      lasCloudSizeMb: 164.0,
      geotiffDemMb: 52.8,
      orthomosaicMb: 240.5,
    }
  },
  {
    id: "proj-narmada-viaduct",
    title: "Narmada Rail Viaduct Piers 14-22 Survey",
    clientRef: "NHSRCL-GEO-441",
    description: "Inspection flight trajectory generating structural mesh and surrounding riverbed topography for flood scour detection.",
    locationName: "Bharuch, Gujarat",
    country: "India",
    coordinates: {
      lat: 21.7051,
      lng: 72.9959,
    },
    crs: "EPSG:32643 (WGS 84 / UTM Zone 43N)",
    areaHectares: 8.2,
    gsdCmPerPixel: 1.25,
    reprojectionErrorPx: 0.51,
    pointCloudSize: 2100000,
    triangleCount: 420000,
    status: "processing",
    progressPercent: 68,
    currentStage: "Multi-View Stereo: Generating dense depth maps (4/5)",
    droneModel: "Skydio X2 Color/Thermal",
    cameraSensor: "Dual 12MP 4K HDR",
    focalLengthMm: 28.0,
    flightAltitudeM: 42.0,
    avgFlightSpeedMs: 3.8,
    captureDate: "2026-09-28 14:10 IST",
    videoDurationSec: 150,
    fps: 30,
    totalVideoFrames: 4500,
    extractedKeyframes: 300,
    thumbnailUrl: "/images/quarry.jpg",
    elevation: {
      minM: 12.4,
      maxM: 58.2,
      avgM: 31.0,
    },
    stages: [
      {
        id: "stg-1",
        name: "Optical Flow & Keyframe Extraction",
        category: "ingest",
        status: "completed",
        progress: 100,
        durationSec: 12,
        logMessage: "300 structural keyframes verified",
        details: "Motion blur and propeller obstruction removed."
      },
      {
        id: "stg-2",
        name: "Feature Detection & SIFT Matching",
        category: "sfm",
        status: "completed",
        progress: 100,
        durationSec: 31,
        logMessage: "890,000 tie-points matched on concrete surfaces",
        details: "Multi-scale keypoint detection."
      },
      {
        id: "stg-3",
        name: "Bundle Adjustment & Camera Poses",
        category: "sfm",
        status: "completed",
        progress: 100,
        durationSec: 22,
        logMessage: "Sub-millimeter camera position convergence",
        details: "Non-linear pose graph optimization."
      },
      {
        id: "stg-4",
        name: "Multi-View Stereo (MVS) Dense Cloud",
        category: "mvs",
        status: "processing",
        progress: 68,
        durationSec: 35,
        logMessage: "Computing disparity maps for frame cluster 18/25",
        details: "Depth map fusion in progress..."
      },
      {
        id: "stg-5",
        name: "Poisson Surface Meshing & Texturing",
        category: "mesh",
        status: "pending",
        progress: 0,
        durationSec: 0,
        logMessage: "Awaiting dense point cloud completion",
        details: "Queued."
      }
    ],
    telemetry: [
      { timeSec: 0, lat: 21.7049, lng: 72.9955, altitudeM: 42.0, speedMs: 3.8, pitchDeg: -28.0, rollDeg: 0.0, yawDeg: 90.0, frameIndex: 1, iso: 100, shutter: "1/800s" },
      { timeSec: 50, lat: 21.7050, lng: 72.9958, altitudeM: 42.3, speedMs: 3.7, pitchDeg: -30.0, rollDeg: 0.5, yawDeg: 92.0, frameIndex: 1500, iso: 100, shutter: "1/800s" },
      { timeSec: 100, lat: 21.7052, lng: 72.9961, altitudeM: 41.9, speedMs: 3.9, pitchDeg: -29.2, rollDeg: -0.4, yawDeg: 89.5, frameIndex: 3000, iso: 100, shutter: "1/800s" },
    ],
    gcps: [
      { id: "gcp-301", name: "GCP-P14 (Pier Base)", lat: 21.7050, lng: 72.9956, elevationM: 14.2, residualErrorM: 0.009 },
    ],
    artifacts: {
      objMeshSizeMb: 54.0,
      plyCloudSizeMb: 88.0,
      lasCloudSizeMb: 72.0,
      geotiffDemMb: 22.0,
      orthomosaicMb: 110.0,
    }
  },
  {
    id: "proj-ghats-hydro",
    title: "Western Ghats Micro-Catchment Topography",
    clientRef: "CWC-WAT-2026-904",
    description: "Canopy-penetrating single-pass survey for catchment runoff modeling and soil erosion index.",
    locationName: "Idukki Catchment, Kerala",
    country: "India",
    coordinates: {
      lat: 9.8492,
      lng: 76.9804,
    },
    crs: "EPSG:32643 (WGS 84 / UTM Zone 43N)",
    areaHectares: 34.0,
    gsdCmPerPixel: 2.80,
    reprojectionErrorPx: 0.81,
    pointCloudSize: 5200000,
    triangleCount: 1040000,
    status: "queued",
    progressPercent: 0,
    currentStage: "Scheduled in cluster queue (Position #2)",
    droneModel: "DJI Matrice 300 RTK",
    cameraSensor: "Zenmuse L1 LiDAR + RGB",
    focalLengthMm: 24.0,
    flightAltitudeM: 95.0,
    avgFlightSpeedMs: 6.5,
    captureDate: "2026-09-29 08:30 IST",
    videoDurationSec: 210,
    fps: 30,
    totalVideoFrames: 6300,
    extractedKeyframes: 420,
    thumbnailUrl: "/images/alpine.jpg",
    elevation: {
      minM: 710.0,
      maxM: 940.0,
      avgM: 812.5,
    },
    stages: [
      {
        id: "stg-1",
        name: "Optical Flow & Keyframe Extraction",
        category: "ingest",
        status: "pending",
        progress: 0,
        durationSec: 0,
        logMessage: "Awaiting GPU worker assignment",
        details: "Pending."
      }
    ],
    telemetry: [],
    gcps: [],
    artifacts: {
      objMeshSizeMb: 0,
      plyCloudSizeMb: 0,
      lasCloudSizeMb: 0,
      geotiffDemMb: 0,
      orthomosaicMb: 0,
    }
  }
];

export const DEMO_PRESET_VIDEOS = [
  {
    id: "sample-quarry",
    title: "Khadki Basalt Quarry (4K Single-Pass Flight)",
    duration: "03:04 (184s)",
    sensor: "DJI Zenmuse P1 - 35mm",
    fps: 60,
    resolution: "3840x2160 UHD",
    altitude: "65m AGL",
    estimatedPoints: "3.4M",
    thumbnail: "/images/quarry.jpg",
    flightPattern: "Nadir + 35° Oblique Linear Corridor",
    notes: "Ideal for volumetric earthwork measurement and cut/fill analysis."
  },
  {
    id: "sample-alpine",
    title: "Zanskar Canyon Alpine Ridge Survey",
    duration: "04:00 (240s)",
    sensor: "Sony RX0 II - 24mm",
    fps: 30,
    resolution: "3840x2160 UHD",
    altitude: "110m AGL",
    estimatedPoints: "4.8M",
    thumbnail: "/images/alpine.jpg",
    flightPattern: "High-Relief Terrain Following Single-Pass",
    notes: "Demonstrates high vertical relief reconstruction across 420m elevation delta."
  }
];
